name: synt
image_channels: 1

dataset_list: 'AbdomenAtlasProTrain_133k.txt'
data_root_path: '/projects/bodymaps/Data'
img_path: image_only/AbdomenAtlasPro/AbdomenAtlasPro/
seg_path: mask_only/AbdomenAtlasPro/AbdomenAtlasPro/
data_txt_path: cross_eval/recon/
dist: True
batch_size: 1
num_workers: 16

a_min: -1000 # -175
a_max: 500 # 250
b_min: -1.0
b_max: 1.0
clip: False
space_x: 1.0
space_y: 1.0
space_z: 1.0
roi_x: 128
roi_y: 128
roi_z: 128
num_samples: 1
phase: train
