vqgan_ckpt: 'pretrained_models/UCSF_V7_133k_250kSTEPS_recon_loss=0.09.ckpt'

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: 32
diffusion_depth_size: 32
diffusion_num_channels: 17 # 1 + 2 * vqgan embed_dim
unet_dim: 128
out_dim: 8 # vqgan embed_dim
dim_mults: [1,2,4,8]
results_folder: checkpoints/ddpm/
results_folder_postfix: 'tumor_diffusion_v11' # v11 10 steps, v10 100 steps
load_milestone: False

batch_size: 8 # 40
num_workers: 16
logger: wandb
objective: pred_x0
save_and_sample_every: 1000
denoising_fn: Unet3D
train_lr: 1e-4
timesteps: 10 # number of steps
sampling_timesteps: 10 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 100000 # total training steps
gradient_accumulate_every: 1 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: True # turn on mixed precision
num_sample_rows: 1
gpus: 0
